# https://starship.rs/config/

add_newline = false

[character]
symbol = "$"
use_symbol_for_status = true

[package]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[cmd_duration]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[rust]
disabled = true
